# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1e2599efbb1c681b515b48d4bc3aa41b233bc70bad05fe9c4c0527e09afe2f14b4234c674fb6483893add147388c937dd05de9ee8e9cf95a6bc9b19b038fb9b2

test:
  secret_key_base: 6ab16cc73b9f1667d9e60ff7a848615e3008e3fc46aacf50e0971ef51a5f343870388e545aec7001d268091fbc219f9bd4e15339165fdb87a0efc3a1c2a7a7c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
